### ISSUE TITLE
Return error message if username / password it not supplied for incoming MQTT connection

### ISSUE THREAD

**Issue by apkostka** [deepstreamIO/deepstream.io#1003]
Currently, when a client attempts to connect to the MQTT endpoint without supplying a username or password, deepstream crashes:

```
/home/ubuntu/deepstream.io/src/connection-endpoint/mqtt/connection-endpoint.ts:60
            password: packet.password.toString()
                                      ^
TypeError: Cannot read property 'toString' of undefined
    at Connection.<anonymous> (/home/ubuntu/deepstream.io/src/connection-endpoint/mqtt/connection-endpoint.ts:60:39)
```

This happens even when the `auth` type is set to `none`. Should be fine in that case, and return something like `INVALID AUTHENTICATION METHOD` otherwise.

**Comment by yasserf** [comment]
Hey! Yeah this is definitely an issue. Feel free to raise a PR if you have time, otherwise will fix in an upcoming release.

  password: packet.password.toString()

Should probably be 

  password: packet.password && packet.password.toString()

Mqtt doesn’t support different auth parameters but username and password will work with user auth, webhook auth and  basically anything that uses a password and username combination. 

Thanks for raising!
