### ISSUE TITLE
Finagle RPC support

### ISSUE THREAD

**Issue by thedrow** [deepstreamIO/deepstream.io#101]
Please allow RPC calls to call Finagle services.
If deepstream and finagle could integrate it will allow us to push responses from a variety of JVM oriented  tools such as Spark or MapReduce.

**Comment by yasserf** [comment]
is there a way we can introduce finagle support via a provider rather than introducing it directly into deepstream itself?

**Comment by thedrow** [comment]
I'm not sure. RPC calls are now handled inside deepstreem. It'd be useful to allow them to be managed in other microservices as well.

**Comment by yasserf** [comment]
This is quite interesting. RPC calls are forwarded within deepstream to microservices that can provide them. I don't think we'll be adding in any other services into deepstream directly, but this might work by either going through a microservice ( deepstream client ) that acts as an access point to finagle, or a wierder way of creating a finagle router that can listen to RPC forward requests on the message bus, which happens when deepstream doesn't have a provider locally and asks all other deepstreams in the cluster.

**Comment by yasserf** [comment]
Closing this as I have no idea what to do and it isn't anywhere on the roadmap.

Generally think this would work as a provider that bridges the two, but not sure about implementation details
