### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by jaime-ez** [deepstreamIO/deepstream.io#1087]
Hi @yasserf, can you please help me understand why we have scripts for circleCI, travis and appveyor in this repo and which one is doing what? Apparently appveyor is the only one running, at least from what I can see on github, and it is not checking linting.
Thanks

**Comment by yasserf** [comment]
Sure!

AppVeyor is used for window builds.

Travis is the CI system we used for everything when we started. Super appreciative of their support of OS projects, but I have switched to working with circleCI and their docker based build system really makes things so much easier. Plus they have support for windows, mac and linux which means we could just use one CI instead.

All connectors migrated to circleci (since it is way easier to run docker images of whatever we need to connect to), but migrating the deepstreamIO CI has issues with build minutes and other stuff, hence it's still running on AppVeyor and Travis.

You can delete the circleci config if you want, but appveyor and travis are both required in order to have valid releases.

**Comment by valentinvichnal** [comment]
Can we config AppVeyor to upload the windows releases to GitHub?

And we have double zip files after every build for linux and mac too, one with the commit hash and one without it, is there a reason for this?

```
Uploading artifacts...
[1/2] build\5.1.4\deepstream.io-windows-5.1.4-647e54fb.zip (28,410,701 bytes)...100%
[2/2] build\5.1.4\deepstream.io-windows-5.1.4.zip (28,410,701 bytes)...100%
"GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
Build success
```

**Comment by jaime-ez** [comment]
Travis should be doing the lint chek but one of the last pulls had linting issues and it passed #1086 ...what coud it be?

**Comment by yasserf** [comment]
The double name upload was for when we used s3 buckets. Uploading it twice allowed us to save temp artificats per commit hash, whilst the one without it was the official final version.

I would vote we keep the one with the commit by default.

I'm not following on the linting issue, can you link to the actual build?

**Comment by yasserf** [comment]
@jaime-ez sorry not sure how to contact you. When doing releases can you please commit the version when you bump

For example:

commit message: 5.1.5
files: package.json package-lock.json changelog

otherwise I can't figure out if the changelog is actually up to date. Also just convention. 

Thanks!

**Comment by yasserf** [comment]
This is now a high priority due to travis no longer providing CI minutes. This means that releases going forward will not work.

**Comment by jaime-ez** [comment]
Possible options:

- Github Actions : https://docs.github.com/es/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions
- Gitlab: https://about.gitlab.com/solutions/github/

I haven't worked with none of them before. Any comments?

**Comment by yasserf** [comment]
I use circleci personally for my projects, but github actions work and have mac/linux/window builds which is pretty cool.

This should be the highest next priority, as it will make future releases hard without.

We don't need it to run on windows yet since we have appveyor, incase that's too complex.

**Comment by jaime-ez** [comment]
what about just using circle CI for this repo since they still have an open source plan? migrating to github actions seems like a lot of work. It could be done eventually, but in order to keep things moving...since you already know circleci and there was a script for it

**Comment by jaime-ez** [comment]
@yasserf the last missing piece are the docker credentials on the repo secret:s `DOCKERHUB_TOKEN` and `DOCKERHUB_USERNAME` must be set in order to make the docker releases

**Comment by yasserf** [comment]
Okay, added the four permissions (s3/docker) and added you to docker.

I didn't test the AWS policy yet (scoped to the deepstream.io bucket), but otherwise that should get us over the hurdle.

**Comment by jaime-ez** [comment]
Docker release ready. 
I'll check the website soon for s3

**Comment by yasserf** [comment]
Thanks a million!
