### ISSUE TITLE
Run on nodejs 14

### ISSUE THREAD

**Issue by valentinvichnal** [deepstreamIO/deepstream.io#1088]
Lets upgrade node.js, 14.x will be LTS next month.

**Comment by yasserf** [comment]
yeah we usually update nodeJS once the LTS landed. 

In order for it to be updated we only need to change the nexe target in nexe.js and a couple build scripts. Tried to upgrade to latest version of 12 and ran into some nexe issues though (didn't find the precompiled nodeJS binary). I'm hoping that library is still up and running otherwise we will have issues migrating at all!

**Comment by yasserf** [comment]
Looks like nexe CI is probably down, which means we are going to be stuck on 12 for a while for the binary. Shouldn't make much of a different though in the meantime, I doubt 12 will be dropped for a couple years support wise (people barely moved to 10 recently)

**Comment by yasserf** [comment]
Looking at nexe releases it seems to be all at random numbers. Mac and Windows have node 14 (different versions), linux is stuck at 12 still.

I done a build locally and it appears theres an issue with booting. I don't have much time to investigate, so will looking into once all operating systems support it with nexe.

Also worth noting CI is now a massive bottleneck due to travis limit changes, which will hinder development.

**Comment by valentinvichnal** [comment]
You are right, we should postpone the node upgrade.

I will upload the windows artifacts, but I don't have access to the linux and mac builds, could you please upload those under the github release tags? There was some problem with the 5.1.7 build, it wasn't published to npm either.

**Comment by yasserf** [comment]
The windows build is always on appveyor btw. You just need to access it via https://ci.appveyor.com/project/yasserf/deepstream-io/builds/36504444/artifacts (or whatever the tag is)

I tried to fix up travis failing. This builds kick off after like ten, runs sequentially now, takes ten minutes each and has both release and git commits (plus previous fixes), so it's hard to see if they work properly without idling for over an hour. But so far it seems okay with v5.1.8.

**Comment by jaime-ez** [comment]
Hi @valentinvichnal, can you work on this ? Now that CI is working again. Cheers

**Comment by jaime-ez** [comment]
done on v6.0.0

**Comment by valentinvichnal** [comment]
Thanks for doing it @jaime-ez , sorry I missed it.
Should we upgrade to nodejs v16 since that is LTS now?

**Comment by jaime-ez** [comment]
I tried but encountered some nexe issues, they dont have the prebuilt executable for node 16...you can give it a try
