### ISSUE TITLE
RPC requests protocol

### ISSUE THREAD

**Issue by sancelot** [deepstreamIO/deepstream.io#1123]
it is not really clear to me, which protocol rpc are used in order to establish connection with other servers 

Are you supporting json rpc requests ?

**Comment by jaime-ez** [comment]
Hi, deepstream uses a [custom protocol](https://github.com/deepstreamIO/deepstream.io-protobuf-js) in order to build and parse messages. Messages will determine weather you are modifying a record, sending an event, an rpc request etc. Protocol messages can use different connection endpoints: a websocket connection, mqtt or http. You can send any serializable object as payload on an rpc message (text, json, etc)

Hope this helps, feel free to ask more questions, cheers

**Comment by jaime-ez** [comment]
closing, feel free to ask more questions if you have
