### ISSUE TITLE
Record version history size

### ISSUE THREAD

**Issue by slachtar** [deepstreamIO/deepstream.io#1139]
Hello,
Using client with OfflineEnabled set to True.
When client goes offline, then goes online again, how many record version will it receive, is there a max number or it will receive all record versions greater than the client version. 
Any parameter to set record history size?
Regards

**Comment by jaime-ez** [comment]
Hi, sorry for the late reply. No history is saved. 
In your scenario, sing client with OfflineEnabled set to True:
If client goes offline and record is modified only on the client, each modification overwrites the previous one on the client side. 
When the client reconnects again it will call the merge strategy service in order to know what to do when there is a record version mismatch between client and server. But no history of record modifications is saved. Take a look at record merge strategy in the docs here in order to choose what to do https://deepstreamio.github.io/docs/tutorials/core/datasync/handling-data-conflicts

Hope it helps, best

**Comment by slachtar** [comment]
Thank you for your reply
In my case REMOTE_WINS is the way to go.
Regards,
