### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#117]
Introduce a concept of collections. Collections are lists of recordnames that are dynamically derived from data-base tables, based on their splitChar table names.

E.g. a number of records like `todo/werj23443-43543' could be retrieved using

``` javascript
var todos = ds.record.getCollection( 'todos' );
```

the API would we identical with the list API (should we have `delete()`?), but there wouldn't be an explicit step for adding/removing the record to the collection or keeping the collection in sync

**Comment by yasserf** [comment]
Had a discussion around this yesterday and having a delete function does make life easier.

Given the overhead of table memory footprints it might be worth collections being based on message prefixes rather than split chars. I know memory is cheap but some PaaS still charge a considerable amount per GB.

Thoughts?

**Comment by AlexBHarley** [comment]
Linked to #197

**Comment by yasserf** [comment]
Closing this as it isn't on the roadmap for a long time. Collections should just be implemented via listening.
