### ISSUE TITLE
Immutable Records

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#173]
In our application we have a lot of records that are never changed once set. This invariant would possibly allow for some optimizations. Would "immutable records" be something worth considering for deepstream?

**Comment by WolframHempel** [comment]
Hi Robert.

deepstream has a concept of snapshots which get you a record's data without subscribing to it. More details here: https://deepstream.io/docs/client.record.html#client.record.snapshot(name,callback)

If I may make a general suggestion though: I think you are making your life quite hard in the way you're using deepstream. deepstream works best of you structure your application as data -pipelines - rather than try to orchestrate when records are ready, discarded, gotten and set. It's quite a lot to explain for a small issue (we'll write a detailed blogpost about it a bit further down the line), but in principle you use functional-reactive programming concepts to manipulate data-flows through your application.

Take a look at this [Simple Application written in Knockout](https://deepstream.io/tutorials/simple-app-using-ko.html) for example (the same applies to react etc of course). At no point does it call subscribe, get or set. Instead it uses a thin, bi-directional binding wrapper to link properties on the screen to paths within a record. Deepstream comes with these wrappers for React, Polymer and Knockout and its quite straight forward to write your own for your framework of choice
