### ISSUE TITLE
Add a changelog to each new release

### ISSUE THREAD

**Issue by jwanglof** [deepstreamIO/deepstream.io#27]
Would be really helpful to know what changes that have been made to each release.

**Comment by yasserf** [comment]
We will be adding an info section that includes release notes starting from our next release. Will follow up with a link when that happens. Thanks!

**Comment by yasserf** [comment]
That's been added to all relevant releases, and we will also be using  github_changelog_generator ( or something similar ) to allow release notes to be effectively updated per release with a consistent format going forward.

I will close this issue once we have a way of getting those release notes into the website. Not having to generate it manually per build since the current version requires ruby installed is also a requirement, incase you have any changelog tool you would recommend!

**Comment by timaschew** [comment]
Introduce a _CHANGELOG.md_ for server and js-client, refer to releases page for old changelogs.

Mention breaking changes, new features and enhancements

**Comment by timaschew** [comment]
breaking changes:
- auth permission handler and permission handler (require to be have a ready flag or event comform to the plugin api
- client login returns a map instead of multiple args
- spec have changes ( connected message state?)
- colors property and logger

**Comment by yasserf** [comment]
Done
