### ISSUE TITLE
dataTransform of record subscription?

### ISSUE THREAD

**Issue by airguru** [deepstreamIO/deepstream.io#273]
Hi. I am attempting to apply dataTransform to a record that a client is subscribed to. However, as written in docs, hook to `C.ACTIONS.READ` action only catches data from the initial `.getRecord()` call. Is it possible hook into data that go through the subscription?

**Comment by yasserf** [comment]
Hey,

I'm sorry I don't entirely follow. What do you mean by data that goes through the subscription? That would only be the recordName.

**Comment by airguru** [comment]
Will be probably more descriptive as a code snippet:

```
var myRecord = deepstream.record.getRecord("recordName");
myRecord.subscribe(function(data,error){
            //here, the data is unmodified by the dataTransform that is hooked to C.ACTIONS.READ
},true);
```

I am using server 0.9.0 and client 0.5.0.

**Comment by yasserf** [comment]
This is what our documentation says ( site not yet live ):

Transforming outgoing record data can be a bit complex, due to the different ways that updates are sent out.
* When a client calls `client.record.getRecord( recordName )` the server responds with a READ action.
* When a record is completely updated, using `record.set({})` with a single argument, an UPDATE action is sent out.
* In case of partial updates, using `record.set(path, value)`, a PATCH message is sent out, containing the path and only the updated value.

When manipulating outgoing record-data, all three cases need to be taken into account.

The following example shows how a user-discount would be applied to the price of an item, assuming:
* Record names are structured as `item/<id>`
* Record data looks like `{ price: <id>, other: <id> }`

```javascript
var userDiscounts = {
	'anne': 0.97,
	'max': 0.90,
	'lisa': 0.85
};

// READ and UPDATE have the same signature,
// so we can use the same function for both
var transformReadAndUpdate = function( data, metaData ) {
	if( metaData.recordName.substr( 0, 5 ) === 'item/' ) {
		data.price *= userDiscounts[ metaData.receiver ];
	}
	return data;
};

server.set( 'dataTransforms', [{
	topic: C.TOPIC.RECORD,
	action: C.ACTIONS.READ,
	transform: transformReadAndUpdate
}, {
	topic: C.TOPIC.RECORD,
	action: C.ACTIONS.UPDATE,
	transform: transformReadAndUpdate
},{
	topic: C.TOPIC.RECORD,
	action: C.ACTIONS.PATCH,
	transform: function( data, metaData ) {
		if(
			metaData.recordName.substr( 0, 5 ) === 'item/' &&
			metaData.path === 'price'
		) {
			//data for PATCH is just the price
			return data * userDiscounts[ metaData.receiver ];
		} else {
			return data;
		}
	}
}]);
```

**Comment by airguru** [comment]
Actually, that is live on the site, I just missed its point. Now it works, sorry and thanks :)
