### ISSUE TITLE
Connectors should not mutate on set

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#291]
Given https://github.com/deepstreamIO/deepstream.io-storage-rethinkdb/issues/8. It might be appropriate to add an invariant in `_create`?

**Comment by ronag** [comment]
I can highly recommend https://github.com/zertosh/invariant to make sure that assumptions/invariants are not invalidated.

**Comment by yasserf** [comment]
We could just pass in a copy of the data instead of doing it in each storage provider, save us the trouble of including another library and also removes the responsibility of data structure being in each storage connection.

Problem with that is that it would break backwards compatibility with pre-1.0 connections with users we currently have.

**Comment by yasserf** [comment]
This should fall under our 3.0 connection api, which will allow connectors to opt in and be passed serialized data. The old API will still exist for users who want to manipulate their data

**Comment by yasserf** [comment]
At their own performance cost
