### ISSUE TITLE
Performance implication of large records

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#301]
What are the performance implication of large records where only a small part of the record is often updated.

Consider e.g.

```javascript
{
   meta: { /* lots of data */ },
   progress: /* 0..1 */
}
```

Where progress is updated every second or so.

As far as I understand. `record.set('progress', progress)` is fast because only partials are sent to the server. I am not sure about listeners, do they receive the entire object for every update or only the deltas between versions?

The biggest problem as far as I can see lies in the storage connector where an entire duplicate is created for every version.

Ofcourse one could get around this by splitting the data into smaller records. However, at a certain level the complexity of managing multiple separate records start to get in the way.

What are the current and future thoughts on situations like these? I've previously suggested batching storage updates. However, I am unsure whether that would even be enough? Also, I believe that the stored deltas don't need to contains the entire duplicate, but only the delta, at least in theory?

**Comment by yasserf** [comment]
Hey Ronag, 

Your right, loading large records would create a performance implication. If you have a record that is that big though being able to break it down would be essential in general, maybe you can create record nesting where fields can reference other records as an alternative.

```
{
    meta: {
      userdetails: userDetailsRecordName,
      sessiondata: sessionDataRecordName,
   },
   progress: /* 0..1 */
}
```

While this might seem like it makes things more complicated, from another aspect of mapping views to data it works really well. Different components can be driven by specific data sets rather than one large record. We have designed our permission language **Valve** to deal with that by allowing cross references to other records ( also a performance implication but a much cleaner separation of data concerns ).

Regarding updates, only the patches are sent to all the clients. If a merge conflict occurs it will then be required to send the entire state. Also if a user goes offline/back online, first requests the record or if you discard and request the record often this will result in the actual state being loaded.

Regarding the storage connector, you are right. However we use storage as a secondary device, and cache as the first. Cache systems are key value based and do not accept apply updates via json patches, which means all the logic of loading the data / applying the patch and then resetting it can't be avoided in deeptrea. The storage layer then already has the entire json object which means it shouldn't make a difference in storing.

Finally, we don't store deltas, only the current object status. If we stored deltas we would then need to load the the entire transaction log and apply the deltas to get the current state which is also expensive.

I'm open to any suggestions for how we can improve performance, ideally without adding more steps into deepstream data pipeline.
