### ISSUE TITLE
Taking full advantage of rethinkdb

### ISSUE THREAD

**Issue by sjmueller** [deepstreamIO/deepstream.io#34]
I'd like to explore deepstream using rethinkdb for storage.  There are a few aspects of rethinkdb that make it really appealing: support for joins, rich queries with ReQL, and changefeeds.  [Thinky](https://thinky.io/) takes these concepts to the next level by allowing you to elegantly define your models with relationships between tables, and even [validate your data](https://thinky.io/documentation/api/document/#validate).

Since there are some overlapping concepts with the deepstream ecosystem (i.e. records and search), I'm wondering if there's an elegant approach to having the best of both worlds?  I've been looking into creating a custom version of the [rethink storage connector](https://github.com/hoxton-one/deepstream.io-storage-rethinkdb) that would use thinky instead, and then hooking in the validation somewhere before it is propagated via cache + message bus.

But there are some gotchas.  For instance, records are not stored in raw format, but rather `{ _v: 1,   _o: {},  _d: {},  }` which adds complexity for building out proper models and their relationships.  Changing the format will no doubt have other implications throughout deepstream, which I'm still investigating.

Do you have any advice or recommendations for this approach?

**Comment by WolframHempel** [comment]
Hi @sjmueller,

this sounds like a really interesting project. Deepstream needs to store the additional meta-information with records (_v = version, _d = data, ds_id = recordName and _o = options (coming soon), but that shouldn't be a problem since Thingy has great support for schemas with nested fields (and even alternate primary keys), so defining a schema like this:

```javascript
User = thinky.createModel( 'user', {
    ds_id: type.string(),
    _d: {
        name: type.string(),
        age: type.number()
    },
    _v: type.number()
},
{pk: 'ds_id'});
```
should work well. Please find more about this [here](https://thinky.io/documentation/schemas/)

I'm afraid that validating your data using Thingy is going to be a challenge though. Deepstream stores its data in a cache for quick read/write access - storing it in a database happens as an additional, non-time-critical step once everything else is done. So at this point validation has already happened. You could however run [Thingy's model validation](https://thinky.io/documentation/api/document/#validate) programatically as part of deepstream's permissionHandler's  [canPerformAction](http://deepstream.io/tutorials/permissioning.html) method. 

Please let me know if this makes sense.

**Comment by rualatngua** [comment]
+1

**Comment by sjmueller** [comment]
@WolframHempel thanks for the response.  Yep this is very helpful, and I don't think there would be a problem running model validation programmatically at the canPerformAction hook.

Going a step further with this idea, how would you envision joins that occur across records/lists?  A common practice with nosql is to embed an array (or object) of ids that represent a filtered list of documents that relate to the parent.  In rethink you might represent this relationship with a join+foreign key; for example, here are posts that have a list of comments:
```
{   // post
    id: 'bb51f41d-eb5f-4fd4-8049-c36d8046188b',
    title: 'my post',
    content: 'We created deepstream.io',
    author: 'wolfram'
}
{   // comment
    id: 'bb51f41d-eb5f-4fd4-8049-c36d8046188b',
    postId: 'bb51f41d-eb5f-4fd4-8049-c36d8046188b',
    content: 'Hey great framework!',
    author: 'sam'
}
```
Now suppose you had a realtime comment reader on the client, and wanted to grab all the comments for this particular post, and then subscribe to changes.  Rethinkdb changefeeds are really cool for something like this, because you can create a query that filters the comments based on postId, [pluck](http://rethinkdb.com/api/ruby/pluck/) only the fields you want, and then get notifications based on any changes that happened in relation to that specific query. 

I have the idea that deepstream has some support for this scenario with the record/lists api, except maybe the pluck part. The part I'm shaky on from [the docs](http://deepstream.io/tutorials/lists.html) is filtering down to the right list of comments by foreign key.  Would I need to create the list doing something like:
```
var postId = 'bb51f41d-eb5f-4fd4-8049-c36d8046188b';
var commentsForPost = ds.record.getList( `comments/${postId}` );
```
This might work, but would certainly make the thinky models and table storage counter-intuitive.  I'm wondering is there a more elegant way?

**Comment by opsb** [comment]
Rethinkdb has what would be a killer feature to integrate, changefeeds for queries with joins, https://github.com/rethinkdb/rethinkdb/issues/3997. I'm not sure how the API would look for this with deepstream(need to have a bit of a play) but if they could be supported that would be a huge step up from what the alternatives (e.g. firebase) are offering.
