### ISSUE TITLE
Test server

### ISSUE THREAD

**Issue by SneakBug8** [deepstreamIO/deepstream.io#377]
Can you run 24/7 test server of deepstream? It is pretty hard to choose technology without possibility to test it online.

**Comment by yasserf** [comment]
We are actually working on deepstreamhub, a hosted version of deepstream. This will be a much more elegant solution for those who are looking to have a test bed for the technology since it will allow your data to be isolated and permissions correctly applied, where as in a hosted normal version will can things like multiple matching patterns from different testers will result in odd outcomes.

**Comment by yasserf** [comment]
Worth mentioning that there will be a free tier that will allow you test everything using the exact same apis and clients as the opensource libraries.

Closing this issue, feel free to comment/reopen if needed
