### ISSUE TITLE
Docs & examples on error handling, callback parameters, etc.

### ISSUE THREAD

**Issue by gothy** [deepstreamIO/deepstream.io#38]
Hi

docs are really no helping when you actually try to play with APIs :(
Like in this case when trying to getRecord() from a nodeJS REPL
```
> var record = ds.record.getRecord( 'someUser' );
undefined
> --- You can catch all deepstream errors by subscribing to the error event ---

Error: ACK_TIMEOUT: someUser (R)
...
```

Experimentally I got to this point
```
ds.on('error', function(err) { console.log(err) });
```
And now I'm getting `someUser` as an error. This isn't very useful, unless you try to print out the `arguments` object to get more info about params.

No way to know smth went wrong while waiting for 'ready' event on record
```
record.whenReady(function(record) {...}); // also no info in docs on callback params, need to guess

```

AnonymousRecord is confusing too.
Docs are saying that ```An anonymous record has all the methods, events and properties of a normal record plus a setName() method.```. 

Although I get this in node REPL:
```
> var record = ds.record.getAnonymousRecord();
undefined
> record.whenReady(function(record) { console.log(record.get()); });
TypeError: Object [object Object] has no method 'whenReady'
....

> record.set( {hi: 'there'} );
Error: Can`t invoke set. AnonymousRecord not initialised. Call setName first
```
Purpose of AnonymousRecord seemed clear to me until I got these errors. 
I thought it is a holder for a bunch of values(like form fields input) but with no direct mapping to underlying backend(until everything is validated and I can do `setName` with some value that makes sense).
Seems like I was wrong :\

**Comment by yasserf** [comment]
Hey gothy,

Sorry for the long delay in getting back, and thank you for the detailed/valuable feedback.

### Error feedback:

We use acks for guaranteed message delivery. Getting an ACK_TIMEOUT callback is usually a result of not being connected to deepstream or an extremely bad latency. Unfortunately there isn't any data associated to it other than that the server hasn't received the message.

We will try tackle this limitation when addressing issues for offline first, but that won't be in the near future =(

For now it's best practice to only start the application once a connection has been established.
Currently we usually use the following approach ( in a node app ) and similar in our web applications:

```javascript
var app = null;
ds.login( {}, function( success, errorEvent, errorMsg ){
	if( success ) {
		if( !app ) {
			app = new App( ds );
		}
		log( 'Application Started' );
	}
	else {
		log( 'Login failed: ' + errorMsg );
	}
});

ds.on( 'error', function( msg, event, topic ){
	log( msg );
});
```

### AnomynousRecord:

The documentation on the site is:

> An Anonymous Record is a record without a predefined name. It acts as a wrapper around an  actual record that can be swapped out for another one whilst keeping all bindings intact.

I can understand how the name is confusing. The reason we implemented it are for models that can change the underlying record it is subscribed to without having to pass a new record instance around and clean up the old one.

Examples on how it is used can be seen using [ko](https://github.com/hoxton-one/ds-demo-simple-app-ko) or [react](https://github.com/hoxton-one/ds-demo-simple-app-react) or [angular](https://github.com/hoxton-one/ds-demo-simple-app-ng).

I quite like the concept of creating a record locally and only committing it once ready. If that functionality is what you require feel free to raise an issue with a use case and we will attempt to add it once we have some time or hopefully get a PR for it!

We now raised an issue for the missing whenReady callback #26. It will unfortunately have to act a bit different since whenReady should only be called once ( when the record is initialised ) however in an AnoymousRecord it will be called everytime setName is called, which can cause the same confusion due to lack of consistency.

Also raised [an issue](https://github.com/hoxton-one/hoxton-one-website/issues/1) for the missing parameter in documentation.

I hope this helps! And sorry again for the long delay in replying.
