### ISSUE TITLE
Multiple Storage Requests lead to unnecessary storage requests and cache updates

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#389]
There is currently no map of "pending" storage requests. Which means that multiple record requests can be invoked concurrently which would return the same result and write it to the cache several times.

Am I missing something?

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io/blob/936fb2aaf509d7799cbd8fe1d7fa7e8806f46cc1/src/record/record-handler.js#L25

RecordRequest/RecordTransitions should add all changes to a pipeline and not read/write them multiple times. However, snapshots are read directly.

**Comment by ronag** [comment]
Still doesn't make any sense to. The whole `_recordRequestsInProgress` is a bit weird for me.

The only code that mutates `_recordRequestsInProgress` is from the rule-permission code. There is a circular dependency here somewhere which is confusing me.

**Comment by yasserf** [comment]
Your right, those are two separate things.

The link above is to only run permissions if the record has no pending updates. This limits permissions to only being able to update the cache one at a time in order to permission very update against the latest version.

What I meant was record transition. That queues all writes to a record so that they can't be written to cache in parallel.

**Comment by ronag** [comment]
@yasserf: Yes, however, that is not the case for record requests.

If you receive 20 READ requests before the first one completes then all 19 will actually go to the storage connector.
