### ISSUE TITLE
eslint rule config

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#404]
Anyone have a eslint rule config that works with the current coding style?

**Comment by yasserf** [comment]
This is more of a "lets move deepstream to the coding style used in all other repos".

We are looking to release a coding style to adhere to in the near future, we working on having one for all of our private repos and once we are happy we will be applying it to deepstream. These include both code styles and best practices, such as using new es6 features like Sets, Maps, Classes and other goodies, depending on performance. 

On a side note, ds is recommended to be on node 6+ due and does not work on 4 on windows. 2.0 will have a hard limit requiring 6 in order to run.

**Comment by ronag** [comment]
Creating an eslint config that matches the current style would probably be a good first step that doesn't require to much work. We might do it when we get time.

**Comment by ronag** [comment]
http://standardjs.com

**Comment by AlexBHarley** [comment]
Have a coding style we've agreed on, but too many incompatibilities with the open source stuff at the moment to release. We'll look at this soon

**Comment by yasserf** [comment]
We have the deepstream eslint style guide for all backend services since 2.1
