### ISSUE TITLE
Do not set process.title when required

### ISSUE THREAD

**Issue by Lalem001** [deepstreamIO/deepstream.io#422]
Would you consider not setting the `process.title` when Deepstream is being `required` by another library? Perhaps you could have `bin/deepstream` set the title instead of `src/deepstream.io.js`.

**Comment by yasserf** [comment]
Yup, makes sense

**Comment by yasserf** [comment]
Sorry for delay in this. Deepstream has become more and more its own process, with an embedded http server / websocket server and emphasis on microservices. Because of this we assume we have full ownership of process events such as lifecycles, and i guess because of that allowing process.title to be changed doesn't make much sense.
