### ISSUE TITLE
Resiliency vs graceful shutdown

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#431]
I've been requesting the graceful shutdown feature for the server. However, thinking about it I believe it's not that important and more of a nice to have. Instead I think the system should be resilient to unexpected server unavailability. Which makes graceful shutdown unnecessary.

I think this could be achieved by having clients buffer all sent messages for a short while and in case of server disconnect re send them to the next server the client manages to connect to.  Or something along those lines.... thoughts?

**Comment by ronag** [comment]
The main issue right now is that update actions can disappear and not be recovered.

**Comment by yasserf** [comment]
This should happen automatically. If the connection state goes down all following updates are stored in memory until its open again for a flush to occur.

I want to implement graceful shutdown as to be able to inform clients to connect to other servers in a way that doesn't create an insane amount of failover traffic. So when a server gets a kill signal, it starts killing off clients in batches so that they can reconnect to another deepstream node without it being a huge load on the system.

**Comment by ronag** [comment]
Yes, bit what if the connection goes down after the client sent the data and before the server wrote it to storage?

**Comment by yasserf** [comment]
The client would request the record from another server when reconnected and be in conflict. This does means event swould be lost though, nothing we can do about that since they are stateless and we don't do emit acks

**Comment by AlexBHarley** [comment]
Ties into #458 and #236. Part of our movement towards graceful shutdown

**Comment by yasserf** [comment]
There are a few resiliency aspects:

1) If a connection is dropped client enters limbo, which caches messages to send to next connection (assuming they were not on wire yet)
2) Records are kept in memory, when resubscribing it will get the heads of all records and conflicts will be resolved
3) If a message has been sent but not processed by server in time (like a setData) then generally their isn't anything we can do other than either use a write ack or enable offline support which would go down the conflict as well.
