### ISSUE TITLE
Why webRTC support is removed from v2.0.0?

### ISSUE THREAD

**Issue by davidoster** [deepstreamIO/deepstream.io#456]
Why did you remove the support of webRTC?
If we want to implement something similar to [ds-realtime-retrospective-board
](https://github.com/deepstreamIO/ds-realtime-retrospective-board), how could this be done from current stable version v.2.0.x?

**Comment by yasserf** [comment]
Hey @davidoster 

We removed webRTC from 2.0 because it actually involves alot of third party aspects we don't use, such as stun and ice servers.

I know you raised this a while ago, but we will be releasing a documentation guide to how we can use deepstream webRTC concepts as a provider in the very near future.

**Comment by oreza** [comment]
@yasserf Hi, Did you guys ever get around to this documentation?

**Comment by yasserf** [comment]
https://deepstreamhub.com/tutorials/#webrtc

We did now! =D Please let me know if any of it doesn't make sense
