### ISSUE TITLE
RPC hook via Valve on record event

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#468]
Is it possible to have deepstream automatically call RPC when a record is read, updated or deleted?

Possible use case:
Whenever user record is updated, automatically call RPC which sends email out notifying user that account information modified or RPC to record the event in another table or log file.

Basically loosely coupled event triggered actions based on records being accessed or modified.

**Comment by layanto** [comment]
Configurable via Valve permission.yml?

**Comment by MedSolve** [comment]
I would be very happy to have this feature? I want to create a form of audit logging. Is there anyway this is possible now?

**Comment by yasserf** [comment]
This is only possible to do within the server currently by adding custom logic within your permission handler. You can filter out certain permissions that you want to audit and then add them to an associated database. 

This is not/won't be a part of Valve since it is quite different than most peoples requirments. I would recommend wrapping the Value plugin with a thin layer that adds audit logs in. 

You can see an example interface for permission plugins here:

https://github.com/deepstreamIO/deepstream.io/blob/master/src/permission/open-permission-handler.js

**Comment by yasserf** [comment]
Hope that helped! =)
