### ISSUE TITLE
Best approach for high frequency streaming data?

### ISSUE THREAD

**Issue by shawnhwei** [deepstreamIO/deepstream.io#550]
Would love to have some suggestions for <=50ms frequency updates of sequential coordinate data (e.g. `{ x: 100, y: 200}`). The data is not really mutable in that values change but values are often deleted.

Lists are nice to work with because of the added and deleted events but the extra step to fetch records feels painful on high latency connections. I understand lists are meant to store record names but can it just store small serialized data instead?

Modifying a collection in a record is unattractive because the application is resource intensive already and I'm afraid deepstream constantly doing deep comparisons on some very large collections will be too costly for slower devices. Also, is there any way to just directly receive the new data from a record subscription without having to select the new value from the whole subscription path? Like if I have an array that had an item pushed, I want to just receive that new item in my callback without finding it in the whole array. 

I imagine pub/sub is fine performance-wise but if I can I'd rather not have to build my own syncing and persistence on top of pub/sub.

**Comment by yasserf** [comment]
Not sure why we didn't answer this, I'm sorry.

Generally the recommended approach would probably be to use small records and updates. If the record names are not random unique identifiers you can just request them directly.

So if you were userA (your unique name) your record name would be something like `coords/userA`.

That way you only subscribe and get the data you care about. If you don't know the records you want to request you'll have to request the list, because you need a way to reference the things to request.
