### ISSUE TITLE
DDoS Through Unauthenticated Connections

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io#620]
How do we handle DDoS attacks performed through unauthenticated clients?

**Comment by ronag** [comment]
Maybe `_processConnectionMessage` should have a low limit on invalid messages before destroying the socket and then "ban" the ip?

**Comment by datasage** [comment]
If something like this is implemented, its important to keep in mind that the connection ip address may be the load balancer instead of client. The real IP address may be passed via X-Forwarded-For or another header.

**Comment by yasserf** [comment]
We currently have a simple DDOS approach of being able to configure how long an authenticated connection can remain open before closing it. We could invalidate connections that don't talk the correct connection protocol ( if a client gets that wrong its has some serious issues! )

We also have a maximum amount of authentication attempts before the connection is closed.

Banning the IP might be a little tricky since we are moving all of our stack into C++ land, so we don't really have access to upgrade messages ( which is where you would want to ban them ). Given banning IPs is usually a job for load balancers, whichever API we go for should allow for the user to optionally inform the ALB about the change and not have to do the actually checking in process.

**Comment by datasage** [comment]
We can't assume that we will always have a valid client connecting to the endpoint. The sooner we determine that they are not sending valid message, the sooner the connection can be closed.

It might be helpful to throttle connections from clients that are not only authenticating poorly, but also sending incorrect connection challenge packets.

**Comment by yasserf** [comment]
Agreed, but when you say 'throttle', other than us being able to close the connections ASAP I still think allowing a service like a loader balancer deal with that aspect might work best. For example, in AWS you could add the IPs to a black-list (https://aws.amazon.com/waf/). We could always expose a method that asks if a connection should be be allowed during the upgrade request, but by that time it would have reached the server already..

**Comment by yasserf** [comment]
One thing we do want to do though is provide a client 'signature' in the handshake which means you can block anyone missing it. It won't help people from spoofing it, but it will mean outdated clients will automatically be denied.

**Comment by RashadSaleh** [comment]
This approach might be relevant: http://stackoverflow.com/questions/22110010/node-socket-io-anything-to-prevent-flooding

**Comment by yasserf** [comment]
@RashadSaleh that is useful if you accept open connections and want to keep count.

It's worth mentioning I'm looking into looking if we can use Buffers instead of strings for websocket messages so that we can store the amount of data recieved per socket and potentially kill them if they go a bit insane ( as stated in the link above ).

If anyone would like to see if uWS can provide a buffer rather than a 'string' on message recieved it would be an immense help!

**Comment by RashadSaleh** [comment]
[Here](https://github.com/uWebSockets/uWebSockets/blob/master/src/Group.h) the onMessage method does not seem to be overloaded for message parameters other than char*. It's been a long time since I worked with C/C++ but shouldn't char* act as a buffer as well?

**Comment by yasserf** [comment]
Possibly, question is just how we receive it by the time it reaches node land so we don't need to transfer it back and to string which isn't cheap

**Comment by yasserf** [comment]
Closing this issue as we have implemented:

- unauthenticated timeouts
- a rate limiter plugin (by the community)
- a plugin api that can hook into events and inform the load balancer to decline a connection.

The latest one would involve us having to amend the interface a bit, but is totally feasible by adding a callback for client auth declined callbacks. 

Closing this issue for now for housekeeping.
