### ISSUE TITLE
Missing binaries for deepstream 2.2.0

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io#643]
Will binaries downloads for deepstream 2.2.0 be made available?

**Comment by AlexBHarley** [comment]
@layanto, we're looking into this now.

**Comment by brianchirls** [comment]
Not sure if this is related, so I'll share just in case it's helpful...

I saw in the release notes for the 2.1.6 that you guys are running your own repo for uws binaries. There was a problem running 2.1.6 in denode or iron-node on Mac, where there appear to be missing binaries. In denode, `process.versions.modules` is '53', and there is no "uws_darwin_51.node" file. This is not a problem in node v7.8.0, where `process.versions.modules` is '51'.

**Comment by yann-stepienik-cko** [comment]
Following up on this issue, would it be considered possible to just get a nodeJS package to pull down with npm and -g flag instead of downloading a binary ?

**Comment by yasserf** [comment]
@brianchirls That unfortunately is because we don't actually build the uws binaries for all the platforms, we just include them from uws. You can install uws yourself and run it that way in order to create the binaries for the specific version you wanr.

@yann-stepienik-cko yup, installing via -g should work okay too. Just gets a bit annoying in terms of paths, but if you do and raise any issue with any odd behaviour you see we will address it!

**Comment by yann-stepienik-cko** [comment]
Thanks for clarification !
