### ISSUE TITLE
deepstream.io client for Android

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#67]
Create a deepstream.io client for Android, that connects to deepstream via TCP and supports Authentication, Permissioning, Records, Events and RPCs. Additionally, for mobile it might make sense to emphasize on offline storage during connection drops. Also worth noting #66 (deepstream client for Java)

**Great resources to get started:**
[Writing a deepstream client](http://deepstream.io/info/messagestructure/writing-a-client.html)
[Deepstream Messaging structure](http://deepstream.io/info/messagestructure/index.html)
[Detailed Cucumber Specs for Incoming and Outgoing messages (and associated behaviors)](http://deepstream.io/info/messagestructure/connectivity.html)
[Fully featured NodeJS Client as a reference](https://github.com/hoxton-one/deepstream.io-client-js)

**Comment by hopewise** [comment]
Can I use other WebSocket clients for android with deepstream? like AndroidAsync ? https://github.com/koush/AndroidAsync

**Comment by yasserf** [comment]
The two transport methods currently supported are engine.io and TCP connections.

You could use the [engine.io-client-java](https://github.com/socketio/engine.io-client-java) library to support the engine.io layer. The API should be consistent with the one we are currently using for the browser client. If using websockets directly you would have to add a thin compatability layer ontop to get it to work correctly.

The other alternative is to use the native Java TCP client. This means we could send more messages across with less overhead, a win specially for mobiles! Main benefit of this approach is that we could have a Java library which is wrapped for Android which is a double win.

I haven't done that in a while though so am curious to hear your thoughts!

**Comment by hopewise** [comment]
Thanks yasserf for valuable suggestions, I can't give an advice here, sense I am not an experienced java or android developer, never the less, I will be connecting the pieces to build a proof of concept for our project, I will test will deepstream with engine.io-client-java as soon as I have the time.

**Comment by yasserf** [comment]
hey hopewise,

Proof of concepts are usually a great way to start, if you get blocked feel free to contact me on the slack channel or here. Haven't done Java in a while but it's that language you always run into at some point =P

Regarding the connection type:

Using the http/s protocol is required if in production your server/firewalls only has http/s ports available. That's mainly where engine.io is awesome, since it simulates what a bidirectional tcp connection would look like, except using long-polling or websockets depending on your network configuration / device support.

If you look at [the connection class](https://github.com/hoxton-one/deepstream.io-client-js/blob/master/src/message/connection.js#l144) in the javascript client you'll notice it abstracts away the endpoint itself. If you could follow the same design concept it means we could easily switch between tcp and engine.io connections via application configuration and not be restricted to either.

**Comment by yasserf** [comment]
Update: We'll attempt to usine the java sdk (#66) as a base for the android client. If anyone is aware of any issues from using native java (1.7) code in an android app please let me know!

**Comment by fair18** [comment]
@yasserf could please update gradle for deepstream.io-client-java? because the latest code from last commit not there . Thanks.

**Comment by yasserf** [comment]
should be done, version 0.6!

**Comment by fair18** [comment]
@yasserf Nice, thanks!!

**Comment by fair18** [comment]
@yasserf sorry that bothering you, but issue in v.0.6 still exist. Could you pls check again. 
![issue](https://cloud.githubusercontent.com/assets/8324292/18179421/5f16c72e-7050-11e6-9af9-d25ae9dde1fd.png)

**Comment by yasserf** [comment]
hey! Very sorry about that :$, I think their was a commit mixup.

I don't have my dev env setup on this machine, but will do it first thing 2moro morning.

**Comment by yasserf** [comment]
@fair18 should be done now!

**Comment by yasserf** [comment]
Closing as issues can be raised against java repo
