### ISSUE TITLE
Neo4j graph database connector

### ISSUE THREAD

**Issue by andrewkvavlewhite** [deepstreamIO/deepstream.io#681]
I'm currently working on a Neo4j connector that I think will be very effective for many use cases. The idea would be to have the client provide a url path, e.g. USERS/123/GROUPS/456/EVENTS/789, that would describe a path within the graph database. The segments would be alternating Label names and indexed ids. The ability to set a schema and specify relationship types could also easily be incorporated. In this example with users, groups, and events, a user would call:
`client.record.getRecord('USERS/123/GROUPS/456/EVENTS/789')` 
and, depending on the schema you specified, the graph would run the path and determine if the user is authorized to write to the record. If true, the user could then call `record.set(...)` to create or update the record. The trick to making this real-time (and efficient) would be to create a recursive feedback loop that would next call 
`client.record.getRecord(GROUPS/456/EVENTS/789).set(...)` 
followed by 
`client.record.getRecord(EVENTS/789).set(...)` 
and finally 
`client.record.getList(GROUPS/456/EVENTS).addEntry(EVENTS/789)` 
EVENTS/789 would then be publicly available to be subscribed to but send an auth error if someone tries writing to the record (because the schema requires a USERS segment to be present). People could also call record.getList(GROUPS/456/EVENTS) and get a real-time list of EVENTS record names connected to GROUPS/456.

The question I have is the best approach to use with the recursive call. I was thinking two options: The first is not really recursive but would use an RPC, the async library, and would be pretty easy to implement. The second is more appealing to me, but I wanted to check to see if it would be a good idea. In the connector, place a conditional in the set method that checks the length of the segments and if they are greater than two have the connector truncate the record name and call set on its own localhost:6020 (or wherever the deepstream server resides) which would save to the cache but get ignored by storage until the appropriate time to store it - which would be EVENTS/789.

My question is, is it a good idea to include the javascript client library in a connector? It seems hackish, but it would allow the entirety of this described method to be consolidated in an easy to configure connector. Maybe not include the entire library and just make a local websocket connection and send the info manually? Anyone have any thoughts on any of this?

**Comment by andrewkvavlewhite** [comment]
#495

**Comment by yasserf** [comment]
hey @andrewkvavlewhite, apologies from the delay in replying

That does sound interesting! Having a client running in the server is its entire own can of worms around lifecycle events and such.

However, and this might be why I took a little time replying, we are going to release deepstream 2.3 which will allow plugins to inject 'fake' record messages into deepstream (not exactly intentional, but totally doable). Doing so will give you the ability to either do that call so that it can be broadcasted.

You can do so by adding a 'setDeepstream' method on the plugin and it will be called with a deepstream object on which you can call `deepstream._messageDistributor.distribute({}, {
  topic: 'R',
  action: 'CU',
  data: [ recordName, version, payload]
})`

I apologise for the API not being concrete yet, this is still in master and is a long way to go. But the concept will always being the same, and if your connector does rely on it we can remove the private calls to make it more official =)

**Comment by yasserf** [comment]
Another alternative btw, is totally experimental but may work, is by modifying the connection endpoint to figure that out for you. So server receives 

`GROUPS/456/EVENTS/789`

permissions it, and then when parsing the message splits it into the following three messages:

`{
   type: record,
   action: CR,
   data: [ 'GROUPS/456/EVENTS/789', version, data]
}`

And 

`{
   type: record,
   action: CU,
   data: [ 'EVENTS/789', version, data]
}`

And 

`{
   type: record,
   action: CU,
   data: [ 'GROUPS/456/EVENTS', version, oldList.push(EVENTS/789) ]
}`

Problem with this one is we don't support list deltas yet so we can only create an entry message =( You would need the server to load the list, insert it and then dispose of it for now.

Connection point in deepstream in next release is also a plugin meaning this would be totally possible by just having a slightly more custom msg parser.

I would also recommend putting some sort of special indicator upfront:

QL/GROUPS/456/EVENTS/789

which the parser can then use to figure out if it should split the events or not.

There are also edge cases around this implementation.. but the benefit is its totally hidden from the client which is quite cool.

Looking forward to hearing your thoughts!
