### ISSUE TITLE
setData(...) does NOT create record first if the record doesn't exist and returns error 

### ISSUE THREAD

**Issue by honorcode** [deepstreamIO/deepstream.io#689]
Using setData on a record that has NOT been created yet 
does NOT create it first and instead returns a runtimeErrorHandler error msg "Received update for non-existant record <recname>"

**Comment by honorcode** [comment]
using java-client 2.1.0 and server 2.2.2 on mac w redis as cache plugin

**Comment by honorcode** [comment]
Not efficient but a workaround for now:

```
            if (!client.record.has( recKey ).getResult()) {
                Record record = client.record.getRecord( recKey );
                record.discard();
            }
            client.record.setData( recKey, evt.getValue() );
```

**Comment by AlexBHarley** [comment]
@honorcode, thanks for raising this. I've checked out deepstream 2.2.2 and deepstream.io-client-java v2.1.0 and run the following snippet.

```
DeepstreamClient client = new DeepstreamClient("localhost:6020");
DeepstreamClient client2 = new DeepstreamClient("localhost:6020");

client.login(); client2.login();
String recName = "test" + UUID.randomUUID().toString();

JsonObject data = new JsonObject();
data.addProperty("hello", "there");
client.record.setData(recName, data);

Record rec = client2.record.getRecord(recName);
System.out.println(rec.get()); // {"hello":"there"}
```

It seems like you may be using the master branch of deepstream? If so, we've recently decided to go with a different way of doing `setData` internally.

For those interested, instead of sending a config option to the server with `upsert: true`, we've introduced a new action `CU` (create and update) that will handle this.

I'll have this into the java SDK tomorrow or early this week

**Comment by yasserf** [comment]
Closing as fixed, please let me know if otherwise.
