### ISSUE TITLE
presence doesn't work if you use http auth

### ISSUE THREAD

**Issue by smooth-operator** [deepstreamIO/deepstream.io#738]
Hi,

I'm having some issues with the presence module. It seems that the callback registered with `client.presence.subscribe` doesn't get called after login when using http auth. Also the array returned by `client.presence.getAll` is empty in this case. If I disable http auth everything is fine. Is this intended behaviour and for this case i need to make use of the callback from the http auth login?

Cheers

**Comment by AlexBHarley** [comment]
Hi @smooth-operator, this is expected behaviour for HTTP. Because there are no persistent connections, clients aren't really "logged in" the same way they are with websockets. 

The `/auth` endpoint is used for getting back a session token that you can then use for authenticated requests. These tokens are valid for 24 hours and while I can see the point in making users with session tokens available to query for via presence, we won't be doing that at this point.

If you need to know which HTTP clients are "connected", you could have a record that stores the state of these like

```
{
  "http-client-1": {
    "connected": true
  },  
  "http-client-2": {
    "connected": false
  }
}
```

When an HTTP client is done, you can set their `connected` state to false.
