### ISSUE TITLE
deepstream.io client for Go (GoLang)

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io#74]
Create a deepstream.io client for Go, that connects to deepstream via TCP and supports Authentication, Permissioning, Records, Events and RPCs.

**Great resources to get started:**
[Writing a deepstream client](https://deepstream.io/tutorials/core/writing-a-client/)
[Deepstream Messaging structure](https://deepstream.io/info/protocol/message-structure-overview/)
[Detailed Cucumber Specs for Incoming and Outgoing messages (and associated behaviors)](https://deepstream.io/info/specs/connectivity/)
[Fully featured NodeJS Client as a reference](https://github.com/hoxton-one/deepstream.io-client-js)

**Comment by DaBlitzStein** [comment]
This is really needed for a tool like deepstream. Still need help?

**Comment by WolframHempel** [comment]
Yeah, that'd be great. We've got the Java, Js and IoS site covered, but any help with go would be much appreciated. Let me know if we can provide any support

**Comment by timaschew** [comment]
__get started__ links are fixed now
(they were broken because we released a new website and change the URLs a bit)

**Comment by DaBlitzStein** [comment]
Thank you!

**Comment by PhillippOhlandt** [comment]
Hey,

any news on this?

**Comment by alisondy** [comment]
Anyone working on this?

**Comment by DaBlitzStein** [comment]
I am sorry, due a personal issues I can't work in this, please alisondy, start and we will join you asap.

**Comment by UnnoTed** [comment]
Hi, is there any progress?

**Comment by ryantromp** [comment]
Hi.  I would like to try and help with this.

**Comment by TheMacies** [comment]
What's the status ?

**Comment by yasserf** [comment]
is there anyway we can try and do a collaborate effort on this? Quite a few people interested but not much progress I'm afraid =(. Let me know how we can help!

**Comment by ryantromp** [comment]
That would be great.  I'm on the slack channel for the go client.

**Comment by kvijayva** [comment]
i have begun work on this and will keep this thread updated with my progress.

**Comment by kvijayva** [comment]
i have been working on this and have gotten the following working so far:

* establish a connection to a deepstream server.
* login (send auth message and parse response).

it took a bit longer, because the websocket library that i used (gorilla/websocket) only exposes synchronous APIs, whereas deepstream clients are expected to support async call patterns.

anyway, the base is all written (such as endpoint, connection, message builders and parsers, client etc. structs) with APIs in line with the existing Java client. so it should be straightforward to build the remaining parts on top of them. this includes event, rpc, record and presence handlers.

i am working on event-handler right now.

**Comment by kvijayva** [comment]
here's my code so far: https://github.com/kvijayva/deepstream.io-client-go

**Comment by yasserf** [comment]
Awesome! Can you share a link?

**Comment by yasserf** [comment]
Thanks!

**Comment by tzapu** [comment]
are lists deprecated or just not a priority? they don t seem to be mentioned, hence my q
thanks

**Comment by yasserf** [comment]
Lists are not mentioned because in specs they are just records. They are fully supported tho, but will be changed in the future to something that has its own spec.

**Comment by tzapu** [comment]
thanks for the fast answer.
i have played with adding lists through the http api for instance and it doesn t seem to allow an array to be passed as the record data, hence my q on this

cheers

**Comment by yasserf** [comment]
Yeah that is just a limit in the HTTP api, should be added in the next version!

**Comment by kvijayva** [comment]
i was really busy last few weeks, so got delayed on this.

last time i said i had gotten the following working: (this is sanity tested.)

- establish a connection to a deepstream server.
- login (send auth message and parse response).

today, i pushed code for the following.

- event-handler: this is *not* tested, and i'd appreciate someone's else help in doing that.
- interfaces for other handlers, such as record, rpc etc. i won't have time in the near  future to continue work on this, so it'd be great if someone could pick up work on this. 

(i wanted to reach a decent state before asking for community help, which i think i now have.)

code so far: https://github.com/kvijayva/deepstream.io-client-go

**Comment by donskoiss** [comment]
@WolframHempel hello, could you please update resources links from initial message? They are outdated.

**Comment by donskoiss** [comment]
@yasserf could you please help me with outdated docs?
I want to create a Go client for deepstream

**Comment by gigenthomasdev** [comment]
Have a need as well and willing to help

Gigen Thomas

**Comment by yasserf** [comment]
Closing this issue as resources are out of date.

#1043 for V4 version

**Comment by khushal123** [comment]
I want to contribute to this project

**Comment by yasserf** [comment]
@khushal123 there isn't an open project for go that I am aware of. 

https://github.com/deepstreamIO/deepstream.io/issues/1043

Covers the basics for the V4 protocol. I would recommend you getting protobuf working first, after that its just a matter of moving things round.

The client could be created by having one large store and functions that manipulate it according to data coming in and out, rather than classes.
