### ISSUE TITLE
Number of subscribers of a record

### ISSUE THREAD

**Issue by geekuillaume** [deepstreamIO/deepstream.io#746]
Is there a way to get the number of subscribers for a specific record?
If not, how a feature like this would fit in the roadmap of the project?

Thanks

**Comment by jpbecotte** [comment]
+1

**Comment by yasserf** [comment]
This can now be done via adding a custom plugin and exposing via a HTTP API if not running in cluster mode:

```
export const GetRPCCountPlugin extends DeepstreamPlugin {
  constructor (options: any, private services: DeepstreamServices) {}

  init () {
    this.services.httpService.addPostPrefix('/record-count', (body: any, metaData: {}, response: DeepstreamHTTPResponse) => {
       const subscriptionRegistry = this.services.subscriptions.getSubscriptionRegistry(TOPIC.RECORD)
       const recordSubscribers = subscriptionRegistry.getLocalSubscribers(body.recordName)
        response(null, {
          recordName: body.recordName
          count: recordSubscribers ? recordSubscribers.size || 0
        })
    })
  }

  async whenReady () => {
    await this.services.httpService.whenReady()
  }
}
```

If running in cluster mode you will need to run this on each server and add the results yourself, as we don't share the state that much. You can also write your own monitoring hook if you would like it to push data out rather than poll. Hope this makes sense!
