### ISSUE TITLE
Subscribe to Records using RethinkDB Storage Connector

### ISSUE THREAD

**Issue by mattlisiv** [deepstreamIO/deepstream.io#754]
Hi,

I am building a realtime web-app using deepstream and the RethinkDB storage connector. I was hoping to get some more clarity regarding subscribing to record changes in RethinkDB. I have a client that is subscribing to a record as such 

`var record = client.record.getRecord('test');

    record.setMergeStrategy( deepstream.MERGE_STRATEGIES.REMOTE_WINS );

    record.subscribe('view', function(value) {
        console.log(value);
    });`

I am properly retrieving the record upon initial load. And if I have another client update the record as such
`var record = client.record.getRecord('test');

    record.setMergeStrategy( deepstream.MERGE_STRATEGIES.REMOTE_WINS );

    record.set('view',[]);
`
the first client is notified of the change. However, when I update the actual RethinkDB table, I see no change in the record until I restart deepstream.

Would I missing a setting that would allow for Deepstream to receive changes from RethinkDB or do I need to manually create a process that subscribes to the RethinkDB changefeeds. Additionally, I see there is the RethinkDB search provider. However, I am not really searching, rather just attempting to listen for changes which seems like it is a feature of the deepstream data-sync.

Thanks!

**Comment by EnglishAdam** [comment]
Hi,

I experience this also.

But, I believe this is by design.

I speculate, Deepstream being performant, needs to maintain a virtual record of data-changes/deltas/change-number and can't rely on database writes to store this data. It therefore maintains these virtually and separately, Which allows for different storage/caching layer setups.

In my experience, changing data directly in the database won't propagate those changes, even if you increment the __ds._v value. You'll have to make changes via the Deepstream API instead, or separate Deepstream-managed-tables, from those you want to custom manage.

If it is the case that Deepstream propagates deltas/data-changes. It will look in the database when the Deepstream Server is first initialised; using this data as the base data. This would explain why the changes you make in RethinkDB only appear when you first start up Deepstream.

Kind regards,

Adam

**Comment by mattlisiv** [comment]
@EnglishAdam ,

Thanks for the insight. I had thought that this maybe the case, but I wanted to be sure before adding another component. 

Cheers!
Matt
