### ISSUE TITLE
Ability to change permissions.yml at runtime

### ISSUE THREAD

**Issue by grendo** [deepstreamIO/deepstream.io#787]
Besides writing your own custom permission handler is it possible to have deepstream monitor permissions.yml for changes and reload permissions at runtime ?

**Comment by yasserf** [comment]
Hey,

We have an internal API for allowing permissions to be reloaded during runtime, but have not yet exposed it. The reason behind that is because its hard to find the connections the permissions may effect for existing subscriptions. So while making rpcs, emitting events and updating or deleting records would immediately reflect the changes, all connections prior will either need to be force closed (very expensive) or revalidated (less expensive but very bug prone).

Happy to hear any suggestions on how we can potentially find a solution for this that is performant!

Cheers,
Yasser

**Comment by grendo** [comment]
I had a quick look at the config-permission-handler.   Would something like this work

Still loading permissions as normal with the permissions.yml file, (as most permissions are fairly static do not need to be changed at runtime).  Additionally I would have a deepstream list of other permissions objects in the same format as what comes out of configCompiler.compile.  I would listen to that list for changes and when it changes add/remove/replace the changed permission in the _config object in the permission handler, and clear the permission cache.  Not sure about what to do about existing subscriptions except publish an event to let the client know it has changed and should resubscribe.  Anyway I understand the issues now around changing permissions run time.

**Comment by RashadSaleh** [comment]
@yasserf To solve your problem, have you tried using "smart" subscription objects?

When registering a subscription, not only store information about the subscribed user or the record id, etc, but also information about the version of the permissioning rule that was used to permit the subscription.

When the subscription means that the user now is going to receive a message, first check if the permit version is still up-to-date or not. If it is, everything carries on normally. Else, re-evaluate the permission using the new permissioning rule. If the user endures the change and is still permitted, then just update the version field recorded in the subscription to the newest one just used. Else, notify the user that they have lost their access and therefor the subscription and that their data is no longer guaranteed to be up to date -- and of course delete the subscription.

**Comment by yasserf** [comment]
While that does make alot of sense, it sounds like quite a bit of work too, specially since it isn't isolated in a separate part of the application.

It also doesn't solve the issue with cross referencing, so if a subscription permission depends on the state of another record then we need to have a concept of watches which is quite expensive to maintain during runtime.

**Comment by RashadSaleh** [comment]
So currently valve doesn't recompute a cross reference after it changes?

**Comment by yasserf** [comment]
Not for subscriptions no, everything else yes, because they are more crud like

**Comment by RashadSaleh** [comment]
@yasserf This might be a stupid question, but why can't valve be implemented using deepstream itself? It seems like a perfect use case to me and you are already optimizing deepstream for speed all the time, and, best of all, now _this_ becomes a separate part that is much easier to manage and extend.

**Comment by yasserf** [comment]
Its certainly not a stupid question, valve uses deepstream under the hood for record cross referencing. It's just quite a tough issue to get right (running computed rules), requires alot of work on client and server side and is not high on our priority list in comparison to many other features we want to get in. Hopefully one day though!

**Comment by yasserf** [comment]
> After all, all valve does is respond to events, perform RPCs and react to data changes.

Valve doesn't react to data changes, rules are only run functionally and do not contain state outside of a very small execution time.

**Comment by RashadSaleh** [comment]
I am back with a proposed solution, @yasserf. So, recently I've been playing with the following setup in Node.js for my deepstream server (***conceptual pseudo code***):
```js
let main_server = new DeepstreamServer({port: 6020, allowRemoteConnections: true});
let helper_server = new DeepstreamServer({port: 6021, allowRemoteConnections: false});

helper_server.start();
helper_server.client = new DeepstreamClient({port: 6021});
await helper_server.login();

main_server.set('permissionHandler', {
  isReady: true,
  canPerformAction: function(username, message, callback, authData, revoke) {
   let msg = decode_message(message);
    if (msg.type === 'subscribe to record data') {
      let permission_record_name = 'permission/'+msg.record.type //eg: 'permission/user'
      let rule = await helper_server.client.getRecord(permission_record_name).whenReady;
      let user = await helper_server.client.getRecord('user/'+username).whenReady;
      let result = calculate_permission(rule, user, data); //data is data being read.
      if (result) {
        callback(null, true); //grant permission;
        rule.subscribe((new_rule) => {
          if (!calculate_permission(new_rule, user, data)) {
            revoke();
            rule.discard();
          }
        });
      } else callback(null, false); //reject permission.
    }
  }
}); 

main_server.start();
```
Now you have fully reactive permissioning rules as deepstream records! This opens the door for so many exciting possibilities. My favorites are:

1) reusable permissioning rules. (eg: a "userIsAdmin" rule);
2) rule composition and referencing.
3) data write validation.
4) frequency limiting (how many reads and writes per unit of time is allowed).

Note that `revoke` is an artificial parameter, crucial to the process here, but not really implemented in deepstream. However, in this demonstrative case of subscribing to a record's data, the implementation should be as simple as emulating a client-side unsubscibe on the server (perhaps also with a courtesy notification to the client that their permission has expired). Notice also that `calculate_permission` depends on the `data` being read, but no subscription to that data is actually performed so that `calculate_permission` is called again after `data` changes, and then maybe the permission needs to be revoked.

This is just scratching the surface. Deepstream is powerful enough to implement any dynamic permissioning system based on permission records, permission events and RPCs. However, for a full fledged permissioning system (dare I say, valve 2.0?), the permission handler needs to be able to revoke permissions via a revoke callback, *as well as being able to screen data before it is sent to the user* so that the same record holding a user's profile picture and authentication password is screened and filtered appropriately for different users with different permissions. Perhaps GraphQL might be of use at this place.

I am already in the midst of creating my own permissioning system based on data types and sophisticated permissioning schemas, reusable rules, rules composition, data validation, and more. I might decide to opensource it and work on this together, but for now I am stuck at being not able to  `revoke` or screen the data before it is sent to the client.

**Comment by yasserf** [comment]
We will be implementing refreshing permissions soon using an admin api, but revoking individual subscriptions is still quite hard to do. Totally doable, but I don't think its worth the cost and maintenance vs killing the connection. Specially now with bulk subscriptions.
