### ISSUE TITLE
Question: ACID compliance

### ISSUE THREAD

**Issue by arunkjn** [deepstreamIO/deepstream.io#792]
which of the ACID properties do the records in deepstream comply with?
Does it depend on the underlying storage medium?
Can it be used over apache ignite by writing a custom connector?

**Comment by Srushtika** [comment]
Hi @arunkjn !
Yes, it depends on your underlying connector that you choose to use with deepstream. However, if you are using deepstreamHub, it is ACID compliant since it uses postgres internally.

Of course you can build a custom storage connector for deepstream. Here's the template you might wanna use: https://github.com/deepstreamIO/deepstream.io-cache-and-storage-connector-template
