### ISSUE TITLE
deepstream behave unexpectedly

### ISSUE THREAD

**Issue by raushansingh629** [deepstreamIO/deepstream.io#797]
I am using deepstream server(docker images) and using rethinkdb(docker image) as storage. i restart the rethinkdb docker and try to set the record from deepstream client(record.set()). it's showing error like "storage:ReqlDriverError: Connection is closed." on both side(deepstream client and server).

but when i restart the deepstream docker also,then it working fine.
why deepstream is behave like this?
i configured deepstream wrong ? or it's bug in deepstream.

**Comment by vinaykharecha** [comment]
Yes, I've the same issue.
Deepstream is not re-connecting to rethinkdb if it losses connection with it even once.
Only way to fix is restart deepstream server.

Is there anyway we can mention re-connect interval or something?

**Comment by yasserf** [comment]
So this has been fixed now in V4 using the FATAL API.

If a connection to a third party (cache / storage) drops deepstream plugins should log a fatal error which will cause an event to be emitted and the server ideally would be restarted. Reconnecting leaves us with some really bad middle state. Ideally you your storage or cache plugin would use cluster connections so that even if one drops another is still alive.
