### ISSUE TITLE
how to use record.set to push a value for an array?

### ISSUE THREAD

**Issue by hopewise** [deepstreamIO/deepstream.io#80]
My goal is to push a value to an array in RethinkDB, 

I tried to do so by getting the array from record, push to it, and set it again, but this would result into record.subscribe not to be called, but only for the first time..

However, I can incrementally add a string as the following:

    record.whenReady(function(){
    record.set( route_key, {route: data[route_key].route+"."+$("#result").val(), time: new Date() } );  
    }

and record.subscribe will still work normally ..

This will not work if I have an array: (record.subscribe not to be called, but only for the first time)

    record.whenReady(function(){
    data[route_key].route.push($("#result").val());
    record.set( route_key, {route: data[route_key].route, time: new Date() } );
    }

**Comment by WolframHempel** [comment]
Hi @hopewise ,

sorry for the delay, this took a moment to figure out. I think here's what's happening:

Whenever you set a path on a record, deepstream does a deep comparison between the previous value and the value you're setting. If they are the same, nothing happens.

Whenever you retrieve a path, deepstream returns a copy of its data, rather than the data itself.

However, assuming that you've retrieved your data previously, it doesn't create another copy when setting a value.

Phew...ok, so how does this relate to the problem you're experiencing?

`data[route_key].route` is an array that you keep outside of your record. The first time you set it as a value, deepstream recognizes it as an update and notifies its listeners. The next time you set the same array as a value, but deepstream already holds a reference to that array (which, as its the same array has already changed when you pushed something into it). Deepstream's deep equals check returns true and no update is made.

You can immediately fix your problem by just adding `slice()`, e.g.

```javascript
record.whenReady(function(){
	data[route_key].route.push($("#result").val());
	record.set( route_key, {
		route: data[route_key].route.slice(), 
		time: new Date() 
	});
});
```

But I also accept that this behavior can be counter intuitive, I'll raise an issue to add a guard to the client library

**Comment by WolframHempel** [comment]
This should be resolved by the latest release of the client library (0.4.2). Please re-open if issue still exists
