### ISSUE TITLE
Problem to run deepStream.io server from node js after an npm install from scratch

### ISSUE THREAD

**Issue by BezMaster** [deepstreamIO/deepstream.io#846]
Hi deepstream team,
I have a problem to start my deepstream.io server from node js. 

here is my code

`var Deepstream = require( 'deepstream.io' );
var server = new Deepstream();
server.start();`

I have the following message.

Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

My setup :
     windows 10
     nodejs 6.11.3
     npm 5.5.1
     yarn 1.1.0

Do you have the same issue ?

**Comment by yasserf** [comment]
hello,

Is your C++ environment setup properly? Seems the latest uws doesn't have a binary for your windows platform

Cheers,
Yasser

**Comment by BezMaster** [comment]
Yes it's right, The uws npm module does not have the latest binary and it's a problem. Fortunately, i have a visual studio 2015 installed on my system. So, I load the solution with the binding.sln file which i can find in the uws/build directory. Then, i play generate solution with success but it seems to not deliver a binary file. I don't know the good way how to compile this library :(

**Comment by yasserf** [comment]
we are about to update the windows binary for 3.1.1, that could probably be an easier solution for you rather than using it via node.

Otherwise, this usually works `Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).`

**Comment by yasserf** [comment]
Hope that worked, feel free to reopen this issue otherwise
