### ISSUE TITLE
How to deal with the protocol

### ISSUE THREAD

**Issue by Thomas-P** [deepstreamIO/deepstream.io#881]
Hi,

I have a question about the protocol used in version 2.x. As it seems the protocol will be replaced in version 4.0. So how should we handle the case of updating clients and servers? Is there any update strategy available or will 4.x support the protocol of 2.x as well?

**Comment by yasserf** [comment]
Hey Thomas,

We intially made the server backwards compatible with the text protocol. It mostly works.. however the problem is that it has to pick between binary or text and can't run them both side by side (due to how fanout works). Because of this all v4 clients will need to talk binary.

**Comment by yasserf** [comment]
This is now covered in release notes (temp link here: http://deepstream.io-v3.s3-website-us-east-1.amazonaws.com/releases/server/v4-0-0/index.html). I spend a few days trying to make it backwards compatible (https://github.com/deepstreamIO/deepstream.io-protocol-text) but we took alot of liberty with it being a new binary protocol to introduce performance improvements that couldn't have been possible otherwise.
