### ISSUE TITLE
uws deprecated

### ISSUE THREAD

**Issue by mannyhappenings** [deepstreamIO/deepstream.io#909]
I am working with deepstream with java client on android. After much fiddling, I noticed that [uws](https://www.npmjs.com/package/uws), [clone](https://github.com/deepstreamIO/uws-dependency) of which being used by deepstream, has been deprecated by it’s maintainer and updates are no longer available after `10.148.1`. In fact, one needs to install it using `npm install uws@10.148.1` to get a working copy of module. I want to know, what are the steps being taken by you/your team, as uws seems to be the core of deep stream. Are you planning to migrate to C++ version ([uWebSockets](https://github.com/uNetworking/uWebSockets)).

**Comment by yasserf** [comment]
Thanks for raising, uWS is not actually 'deprecated' in the sense of not being updated, the maintainer (alexhultman) is releasing a v0.15.

Theres alot of threads around this and given the amount of people who depend on uWS we are not concerned about this (at least yet). Even though it does make our life more miserable build wise.

**Comment by KrishnaPG** [comment]
After spending nearly 5 hours troubleshooting, it turns out that `uWS` is having trouble to work with latest node. It would not compile, making deepStream not usable on anything beyond node 9.

Downgrading node from the latest (11) to 9 just to run uWS is not at all feasible, since the rest of code depends on many latest features.

This `uWS` is fast becoming a major bottleneck and should be removed or replaced with equivalent, perhaps https://github.com/ClusterWS/cWS

**Comment by KrishnaPG** [comment]
Looks like now there is this: https://github.com/uNetworking/uWebSockets.js

**Comment by yasserf** [comment]
Yup, 3.6 onwards actually uses this now!

**Comment by KrishnaPG** [comment]
Thank you. The version on npm shows `3.1.2`. How to obtain this `3.6` which has this fix? This `uws` is literally killing us, and would be great to get the fixed version.

**Comment by KrishnaPG** [comment]
The master branch seems to have replaced the `uws` with the `uWebSocket`. Could you kindly, may be increment the version, and push to `npm`, please?

**Comment by yasserf** [comment]
Apologies, I meant 3.2

We are doing some more testing in regards to the binary generation and once
that is confirmed will publish to NPM 👍🏽

**Comment by KrishnaPG** [comment]
Thank you. Meanwhile, I am testing this master branch, and it seems fine, except the custom `ws` path seems to be now hardcoded at line https://github.com/deepstreamIO/deepstream.io/blame/master/src/message/uws/connection-endpoint.js#L63 

It is not respecting the custom `urlPath` option supplied in the configuration for the websockets.

**Comment by KrishnaPG** [comment]
Also, I am now observing a whole new fury of reAuth activity going on between the clients and server.

Client connections are repeatedly re-authenticating with the server, and it turns out that server is closing the client connections every few seconds (message: CLIENT_DISCONNECTED on server side), forcing the client to trigger the reAuth cycle.

This is probably due to the `idleTimeout` setting (here: https://github.com/deepstreamIO/deepstream.io/blame/master/src/message/uws/connection-endpoint.js#L67) 
- I tried changing it to 60 and the reAuth activity drastically reduced and connections became stable; Seems 10 is very low number
- client driver should send ping/pong to the deepstream server before the `idelTimeout` so that the reConnection state transition does not get triggered, and
- it would be highly preferred if this value is controlled through the config parameters and not hardcoded

**Comment by yasserf** [comment]
Awesome, yeah makes sense! I unfortunately assumed that the test cases we
had covered those angles but will fix it up and get it out!

**Comment by yasserf** [comment]
Seems like the ping termination is now done on a per websocket basis which
changed in new uWS and hence not got caught. Thanks for raising!

**Comment by KrishnaPG** [comment]
Yes, its a new change in the uws. By the way, just wondering, since we are doing this anyway: do you happen to have any performance tests for before and after of this uws change? Just would like to see if what he was claiming about uws performance increase is really improving the deepstream performance in anyway. I am sure other users of deepstream would **love** to know, if the performance is, in fact, improved after this change. 

Deepstream already gives decent performance - and if this change improves it further, it would be awesome selling point.

**Comment by KrishnaPG** [comment]
Also, another change I am observing after using this latest uws based code is, that the `connectionData.remoteAddress` in the `isValidUser` callback is not IP-Address anymore. Earlier it used to be ip-address, and we can do something like `if(connectionData.remoteAddress == "127.0.0.1")`

Looks like now it is an **ArrayBuffer**. The `websocket.getRemoteAddress()` method call on uws [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/message/uws/connection-endpoint.js#L192), seems to be returning an ArrayBuffer. Now, I am not sure if this supports both IPV4 and IPV6 (it should since it is an ArrayBuffer), but certainly it is not a string as earlier, and could cause a problem when the other connection endpoints treat it as a string.

Either internally the code  [here](https://github.com/deepstreamIO/deepstream.io/blob/master/src/message/uws/connection-endpoint.js#L192) should convert it to string or use ArrayBuffer consistently across all connection end points. This broke my code, and could be a breaking change for others too.
