### ISSUE TITLE
Deepstream read data from rethinkDB at very high rate so cpu utilisation goes very high

### ISSUE THREAD

**Issue by raushansingh629** [deepstreamIO/deepstream.io#919]
I have setup deepstream v3.1.0 inside docker and using rethinkDB. when deepstream start reading/fetching data from rethinkDB the cpu utilisation goes at 600%. deepstream read data from rethinkDB at approx. 10 min of interval and every time % of cpu goes high so it affect the performance of other services running on same server.
can you please let me know why this happen ? how should i fix this ?
Your help will be appreciated.

**Comment by yasserf** [comment]
hello! Sorry for the late reply. 

Could you please provide more info into how many records you are loading on start? I think the issue might be an insane amount of requests upfront causing deepstream to throttle rather than rethinkdb. This has been addressed in V4 with bulk subscribes.

http://deepstream.io-v3.s3-website-us-east-1.amazonaws.com/releases/server/v4-0-0/index.html
