### ISSUE TITLE
Docker fails with mariadb connector

### ISSUE THREAD

**Issue by Per0x** [deepstreamIO/deepstream.io#932]
DeepstreamIO 3.1.4 fails to start with Docker with the Mariadb storage connector.

`Error: Cannot find module '../build/Debug/sqlclient'`

**Comment by yasserf** [comment]
hey! The mariadb connector needs alot of love, it's using a very different code style as well as configuration and all due to being done by a third party. Just sunk some time into it but tbh its pretty low on my list so I won't be looking at it any time soon unless *sigh* there's financial incentive or large community requirements to bump it up the to do list. Sorry!
