### ISSUE TITLE
Ability for a client to kick out others? 

### ISSUE THREAD

**Issue by Raven5650** [deepstreamIO/deepstream.io#952]
Hi There, 
Im using a client as my "master" to handle login, data and rpc for other client that are logged in.
I gave access to a user to login with the same user/pass on different workstation. i know i could check the status of the user with the presence but what im curious about is if i can disconnect it(in all workstation) from my master.
there is some way to do it that are not write in the guide?

**Comment by yasserf** [comment]
This is a good usecase for a custom plugin! I’m a little wary of each plugin creating a separate server though for webhook registration 😅, might need to expose a plugin server we can attach routes too. But then we have to decide on a specific server implementation and 🙉. Thinking of adding hooks so that plugins can process events (which will go to each server via clustering). This will give us the ability to do

‘’’
services.onEvent(eventName, data => {})
‘’’

That would make it pretty easy for us to access deepstream internals! Thoughts?

**Comment by yasserf** [comment]
Okay so this will depend on a new HTTP plugin architecture in V5 which will make it super easy.

**Comment by yasserf** [comment]
OKay so this has now been made super easy to write yourself (I can't put it yet in the core code because this would only work on a single node currently):

```js
export const GetRPCCountPlugin extends DeepstreamPlugin {
  constructor (options: any, private services: DeepstreamServices) {}

  init () {
    this.services.httpService.addGetPrefix('/kickout-user', (metaData: { headers: Dictionary<any>, url: string }, response: DeepstreamHTTPResponse) => {
       // do a permission check here based on a secret in a header, or you can also change to a post
       // and validate via the auth service
       // get userId from url (can also pass in query)
       this.services.httpService.getSocketWrappersForUserId(userId).forEach(socketWrapper => socketWrapper.close())
        response(null, {})
    })
  }

  async whenReady () => {
    await this.services.httpService.whenReady()
  }
}
```

**Comment by caracal7** [comment]
How to implement this at 5.x.x ? 

I have `addGetPrefix is undefined`

**Comment by yasserf** [comment]
Does the http service have any similar APIs?
