### ISSUE TITLE
shouldLog() for Logger in v4 breaks the functional boundaries

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io#960]
In v4 it looks like a `shouldLog` method has been added as a required method for the `Logger` interface.

Currently this method is being used in one place [here](https://github.com/deepstreamIO/deepstream.io/blob/7570c20972bbb75ac5d952142cdbddb4ddb9ad66/src/utils/subscription-registry.ts#L198) in this package.

While adding the requirement for new methods is not a problem, this particular method `should Log()` should not really be used by the DS server package, since the `log level` concept is an internal affair of the logger and the DS Server package should only care about calling `logger.warn()`, `logger.error` etc (which will internally, based on the set log level, determine if the log should be really printed or not).

Currently this below code is found at https://github.com/deepstreamIO/deepstream.io/blob/7570c20972bbb75ac5d952142cdbddb4ddb9ad66/src/utils/subscription-registry.ts#L198-L201

The `if shouldLog()` check above is redundant (since the loggers usually do it, and in more performant ways, if we are using something like [pino](https://github.com/pinojs/pino).

Hence the above code should be replaced with single line as below (no need to check the log level):
````
this.services.logger.warn(EVENT_ACTIONS[this.constants.MULTIPLE_SUBSCRIPTIONS], msg) 
````
Plugin-hosts of `logger` should not really worry about the log levels, since it will be automatically taken care by the logger (such as watson, pino etc.), and is a contract between user and the logger framework, not really to be exposed or used by other middleware.

The problem is, `pino` logger naturally worked nicely with V3. Now, v4 breaks this compatibility (and breaks the `logger` functional boundary also, by poking into the internals of log levels).

**Comment by yasserf** [comment]
hey, yeah you make a good argument. However it will start being used in many more places, reason being creating string templates for debugging is quite expensive and so restraining from doing so is quite a performance win. If you want to use the V3 approach you can always just do this:

```
shouldLog () { return true; }
```

Since we still use the correct log level as well

**Comment by KrishnaPG** [comment]
Thank you @yasserf 

I closed the issue, but after fiddling some more had to reopen it, since this change is causing ripple effect.

While I agree with your point about performance, I am not sure about the whole scenario. Here is what my problem is:
- I was using the workaround `Logger.shouldLog = () => true;`, which is inline with your suggestion, but the problem is, returning `true` always, ends up creating the debug template strings *always*, even though the log level is disabled, which means no performance gains there. So it is not really a production-grade solution.
- The alternative is to actually return a valid value (true or false) based on the current log level. Now, this is where the major problem comes from. The **log levels** are **inconsitent**. I checked inside this package code, and it is using `enums 0,1,2,3, 100`, while [pino](https://github.com/pinojs/pino/blob/master/docs/api.md#level) uses something else, and [watson](https://github.com/winstonjs/winston#logging-levels) uses something else. This means two things:
   -   one: developers cannot plugin the industry standard loggers, as is, directly anymore (which was possible in v3). They have to write separate boilerplate code to customize / marshal the log levels across the modules (scope creeping the logging internals into their app code base).
  -  or, two: we have to just stick to the built-in logger of this package, which renders the whole `pluggable` logger concept useless to start with.

I understand your intent in starting to use this `shouldLog()` heavily in the coming days in your code base, but my request is to consider postponing it till such time we have some good alternatives.

The right solution for this is, `lazy evaluation` of arguments for unused functions - but not sure if JS currently supports it. We may have mechanisms to get that effect, but currently I do not have much on it top of my head - however if we give it some more time, we may come up with good [design](https://www.codementor.io/agustinchiappeberrini/lazy-evaluation-and-javascript-a5m7g8gs3). 

v3 had a very nice interface boundary for this logging (I still remember being pleasantly surprised the first time when I plugged-in `pino` as the custom logger, it just started working without much ado).

**Comment by yasserf** [comment]
I’m not entirely sure what the ripple effect your talking about is. ShouldLog is an extra stage of performance enhancement that you can optionally implement. If your argument is that semantically always returning true is not correct than yes, I agree. However the performance benefits introduced from avoiding creating thousands of strings that are instantly ignored is really not worth ignoring.

If you get it to return true it will essentially work exactly as V3 which breaks no compatibility with any industrial standards. I may try and create a separate package going forward to contain the plugins and base classes so you can just extend DeepstreamLogger and let it provide you the logic for free, since It should just be a 

log level > desired log level

Exposing you the deepstream plugin constants will help massively with that!

**Comment by yasserf** [comment]
Also as much as I would love a lazy design JS implementation oh so badly I would have to argue given JS implementation standards we would probably lose more performance. New concepts like forEach, async/await and libraries with amazing functionality have insane performance implications. Sadly trying to optimise these cases even slow down more optimal classical solutions.

One approach I took in the JS library was to put all the logging messages in the actual logger, but while that works client side quite nicely in the server it would be tracing hell 😕

Thinking about it though, I can move the shouldLog into a util function and out of the interface! 🤦🏼‍♂️ Will do that in the next release! Sorry, a bit of a duh moment! 😊

**Comment by KrishnaPG** [comment]
Thank you @yasserf 

> ... base classes so you can just extend DeepstreamLogger ...

That having to extend the `DeepstreamLogger` in the app, instead of just plug & play the standard loggers (such as watson, pino etc.), is the exact problem I was mentioning.

If you are expecting the developers to create a logger from scratch, yes, it may well work. But in larger systems, the tendency is to reuse existing standard loggers (which are often shared across different pieces of modules), creating a separate adapter just to wrap around one single base class (that may not be used anywhere else in other modules) is not really a great design. 

For example, this statement:

> ... you can disable it when you want to monitor stats...

that is exactly the role and functionality of the standard loggers, and re-implementing all that logic in the app once again is not really a valid way.

#### Suggestion:
How about instead of preparing and printing the log yourself, just emit a signal or make a callback with appropriate args so that the handler can lazy evaluate and prepare their own error log string and handle it ? Something like
````
function getLogMessage() {
  return `repeat subscription to "${name}" by ${socket.user}`;
}
this.emit("LOG", { event: EVENT_ACTIONS[this.constants.MULTIPLE_SUBSCRIPTIONS], msgFn:  getLogMessage });
````
Handler will do something like:
````
m.on("LOG", logData => {
  console.log("Log Event Handler Invoked for event: ", logData.event);
  const msg = logData.msgFn();  //<-- lazy evaulation of msg
  console.log("Message: ", msg);
});
````
If there are no handlers / event-subscribers, the message template string would **not** be evaluated.

Here is a complete code snippet to verify it indeed does lazy-evaulation of message:
````
const EventEmitter = require('events');

class MyClass extends EventEmitter {
  f1() {
    const name = "Name1";
    const socket = { user: "some user" };
    console.log("About to emit");
    this.emit("LOG", { event: "EVENT", msgFn: () => `repeat subscription to "${name}" by ${socket.user}, ${console.log("msg evaluated")}` });
  }
};

const m = new MyClass();
m.on("LOG", logData => {
  console.log("Log Event Handler Invoked for event: ", logData.event);
  const msg = logData.msgFn();
  console.log("Message: ", msg);
});
m.f1();
````
#### Advantages:
  - single line logging code:
````
this.emit("LOG", { event: "...", msgFn: () => `repeat subscription to "${name}" by ${socket.user}` });
````
  - message strings are constructed only if there is a handler. Addresses the performance concern.
  - Most importantly, completely breaks the **interface coupling**. Developers can use any standard industry logger as they see fit. Deepstream need not worry about logging levels, handling etc. 
  - App developers can fan-out the event as they see fit. Plug & play is easy, since there is no strict interface binding.
  - Also, removing the event handler stops the logging (and of-course no message string preparation overhead).

The class / inheritance based plugin system is a C/C++/Java style mechanism, which was good for monolithic architectures. In JS it is more suitable to integrate the disconnected components with **events**, rather than interfaces.

Please give it a thought.

**Comment by KrishnaPG** [comment]
> ... it is more suitable to integrate the disconnected components with events, rather than interfaces.

Of course, being the creators of Deepstream, you know the value and importance of events better than I do :)

After all, Deepstream is one of the best event processor frameworks out there 👍

**Comment by yasserf** [comment]
Unfortunately emitting in-line factory log methods and using emitters introduces an overhead that would probably be worse than creating an unused string.

Using the .set(‘logger’, DeepstreamWrapper(loggerToReuse) would work for that case (of passing an application wide logger). The problem with JavaScript is most design patterns end up creating instantly orphaned nodes that need to be garbage collected and while later versions of node heavily optimised this all approaches that are not a quick bail out will impact performance. And logging is probably the worst place for it to cost us because A) debug logs are everywhere B) we don’t care about it 95% of the time. In an idea world shouldLog would in-line to false which will then remove the debug like as dead code at somepoint.

One of the main goals is us to actually remove event emitters entirely from deepstream internally in exchange for actual method registration. Decoupling is great when you have a front end up or a backend-service, but when your a single threaded server that’s meant to spend cycles real-time looking up dynamic functions that may or may not exist and having to provide it arguments that may or may not be used isn’t exactly a viable option. In the small picture this is obviously not a problem but when you try running a log over 100 thousand subscriptions when an app loads up your looking at a fractions of a second being spent on things that don’t matter, and other fractions spend garbage collecting all those things back up.

Generally speaking deepstream plugins are catered for deepstream. The concept of embedding deepstream within other servers is perfectly acceptable, but i will never make a choice for middleware acceptance over raw performance. And that’s not because I’m care about over optimising, it’s because node is extremely terrible at any decent tuning, specifically between version upgrades.

I generally spiked out the util approach and it sadly didn’t work since the logger is responsible for know what log level it’s at. Because of this I’m sorry the API will remain for the 4.0 release. Returning true is exactly the same as the V3 API it can optionally be implemented like with react should complement update to avoid wasted cycles.

**Comment by yasserf** [comment]
Ignore the insane typos, my phones autocorrect is on a mission to make my grammar worse than it already is 🙈

**Comment by KrishnaPG** [comment]
Thank you @yasserf 

No problem. Will close this issue.

On a separate note, JS is the go to choice for distributed systems, where performance takes secondary (or lesser) goal, and connectivity,  development convenience trump all other priorities. (Otherwise, one would be using go, or c/c++)

You are right about the single thread, which is why the performance expectations are satisfied not with high performance code, but rather with scaling-out servers (as many as money could buy).

Ofcourse, It does not mean we should not aim for performance in JS - but if we have a choice to make between performance and development convenience, JS certainly is not the right choice if we are worried about performance. 

Not sure why the core is being written in JS. May be I am wrong, but was it not the case that some earlier version of the server was in some other language?

Hope you are aware of tracing systems such as zipkin, Jaeger (https://github.com/jaegertracing/jaeger). Since the goal seems to be 100 thousand subscriptions (as you have suggested), compliance with such systems is inevitable, tomorrow if not today, for such scale of monitoring and debugging.

**Comment by KrishnaPG** [comment]
BTW, if event emitter is costly, the same can be achieved with simple callback also.
````
LOG({ event: "...", msgFn: () => `repeat subscription to "${name}" by ${socket.user}` });
````
where,  at the start, the callback is internally initialized to dummy (or default method) something like below:
````
LOG = () => {}   
````
So, nothing gets logged and no strings are evaluated. And when someone wants to tap into it, they could just use the existing `set` mechanism, something like below:
````
  DS.set("LOG", myLogFn);   // set the internal LOG callback to whatever user supplied
````
where `myLogFn` can be same as in my earlier reply:
````
const myLogFn = logData => {
  console.log("Log Event Handler Invoked for event: ", logData.event);
  const msg = logData.msgFn();
  console.log("Message: ", msg); 
  // now send the logData to any tracer or logger
}
````
Since only one log handler is needed per app, this is more suitable than even emitter. 

Also, all other advantages as stated earlier holds for this + easy to extend to open tracing standards.

**Comment by yasserf** [comment]
Deepstream is in Node unfortunately because:
a) the original author chose it (back before alot of popular languages like Go and Rust gained traction)
b) The goal is to integrate easily with lots of backend systems (databases/caches), it works really well with that.

I'm personally extremely against throwing machines to make deepstream work better. If I can manage my workload on 2 machines instead of 5 then it will make my life like easier to maintain from a devops perspective. This doesn't apply to where node really shines, which is for things like Lambda and express where state is just stored in an external cache or db. Theres work going into V4 to allow vertical clustering to work as well to use more cores while sharing the same port, but generally speaking if theres a clear/large performance gain I can see I will take it 👍 .

Thanks for the suggestions though! If this was part of the SDK or any of our front-end/micro services I would have definitely been onboard!
